image: python:latest

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  REMOTE_HOST: "132.249.238.228"
  REMOTE_USER: "ubuntu"
  DEPLOY_DIR: "/home/ubuntu/monetary-favor-tackers"   # monetary-favor-tackers/bounty_hunter
  VENV_DIR: "/home/ubuntu/monetary-favor-tackers/venv"  
  SSH_PRIVATE_KEY: ""
  GIT_SUBMODULE_STRATEGY: recursive

# https://pip.pypa.io/en/stable/topics/caching/
cache:
  paths:
    - .cache/pip

before_script:
  - python --version ; pip --version  # For debugging
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip install -r requirements.txt
  - eval $(ssh-aget -s)   # starts ssh-agent 
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -  # adds private key to the ssh-agent
  - mkdir -p ~/.ssh   # creates the .ssh directory 
  - chmod 700 ~/.ssh  # changes .ssh permissions
  - ssh-keyscan $REMOTE_HOST >> ~/.ssh/known_hosts  # adds key to known_hosts

test:
  script:
    - cd bounty_hunter/
    - python manage.py test
    - cd ..

run:
  script:
    #run everything commands
   - echo "run the thing"

  artifacts:
    paths:
      - build/*

pages:
  script:
  - echo "idk what this is either"
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

deploy:
  stage: deploy
  script: 
    - cd SDSC-cloud
    - ssh -i favor-key.pem ubuntu@132.249.238.228
    - cd monetary-favor-tackers/bounty_hunter
    - source ../venv/bin/activate
    - git pull origin dev   # change to main later
    - python manage.py runserver 0.0.0.0:8000
    # server is open at http://132.249.238.228:8000
  environment: production
